print_help <- function(){
    cat(rep("\n",2))
    cat("============================== Help ============================== \n")
    cat(rep("\n",2))
    cat("Rscript HAPPI_GWAS.R <file.yaml> [COMMANDS]")
    cat(rep("\n",2))
    cat("COMMANDS: ")
    cat(rep("\n",1))
    # cat("-removeDuplicates          Remove duplicates in raw data \n")
    # cat("-outlierRemoval            Perform outlier removal to raw data \n")
    # cat("-boxcoxTransformation      Perform box-cox transformation to raw data \n")
    cat("-generateBLUP              Generate BLUP data from raw data \n")
    cat("-generateBLUE              Generate BLUE data from raw data \n")
    cat("-GAPIT                     Run GAPIT \n")
    cat("-extractHaplotype          Extract haplotype \n")
    cat("                           Require: -GAPIT \n")
    cat("-searchGenes               Search genes \n")
    cat("                           Require: -GAPIT \n")
    cat(rep("\n",2))
}